options:
  logging: CLOUD_LOGGING_ONLY
# provided "roles/logging.logWriter" and "artifactregistry.repositories.uploadArtifacts" to project service account 
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - -t
    - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-mca-project/app:$SHORT_SHA
    - .

- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-mca-project/app:$SHORT_SHA

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - run
    - deploy
    - cloud-cicd-demo-mca-project
    - --image=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-mca-project/app:$SHORT_SHA
    - --region=us-central1
    - --platform=managed
    - --allow-unauthenticated
    - --set-env-vars=APP_VERSION=$SHORT_SHA